project:
  type: website
  render:
    - "*.qmd"
    - "!.md"
  # post-render:
    # - _scripts/post-render.R

# dates (change these if you need to e.g. for a new semester)
date: today
date-format: "[Semester 1,] YYYY"

# Progressive sections feature (Next buttons)
# Set to false to disable the progressive sections functionality
progressive-sections: true

format-links: 
  - assignment-html
  - format: assignment-typst
    text: PDF
    icon: file-pdf


execute:
  freeze: auto
  dev: png
  dev-args: []
  fig-format: png

profile:
  default: 
    - solution
    # - exercise
