project:
  type: website
  # post-render:
    # - _scripts/post-render.R

description: The University of Sydney

# dates (change these if you need to e.g. for a new semester)
date: today
date-format: "[Semester 1,] YYYY"

# Progressive sections feature (Next buttons)
# Set to false to disable the progressive sections functionality
progressive-sections: true

format:
  assignment-html:
    embed-resources: false
    title-block-banner: "white"
    title-block-banner-color: "#000"
    reference-location: margin
    citation-location: margin
  assignment-typst: default # enable for pdf output (typst format)

format-links: 
  - assignment-html
  - format: assignment-typst
    text: PDF
    icon: file-pdf


execute:
  freeze: auto
  dev: png
  dev-args: []
  fig-format: png

profile:
  default: 
    # - solution
    - exercise
