project:
  type: website
  # post-render:
    # - _scripts/post-render.R

description: The University of Sydney

# dates (change these if you need to e.g. for a new semester)
date: today
date-format: "[Semester 1,] YYYY"

format:
  assignment-html:
    embed-resources: false
    title-block-banner: "white"
    title-block-banner-color: "#000"
    reference-location: margin
    citation-location: margin
  assignment-typst: default # enable for pdf output (typst format)

execute:
  freeze: auto
  dev: png
  dev-args: []
  fig-format: png

profile:
  default: 
    - solution
